### ISSUE TITLE
Keras multi-class output and node saving problem

### ISSUE THREAD

**Issue by SwagPolice** [amir-abdi/keras_to_tensorflow#6]
Hi!

I am working on a Keras CNN model able to detect 8 object categories. I would like to convert it into protobuf to use it for an Android app, so I used ```keras_to_tensorflow``` library. The problem is that I get a really small number of saved nodes (10 in total) compared to the total of nodes, and I am currently not able to implement the model into my app.
Moreover, it is impossible for me to load the weights.h5 so I am trying to use the model.h5.

Here is the modification I made to the notebook in order to adapt it to my problem:
```python
input_fld = '/home/Documents/Environment/'
weight_file = 'detection_model.h5'
num_output = 8
write_graph_def_ascii_flag = True
prefix_output_node_names_of_final_network = 'object'
output_graph_name = 'androidtest_model.pb'
```

**Comment by amir-abdi** [comment]
I see the problem is that my naming convention might have been ambiguous.
`num_output` doesn't refer to the number of classes. Since my solution is designed to be a general one, `num_output` is expected to be "number of output streams in your network". This is only used in networks which have multiple input/outputs (forked networks). In majority of cases, `num_output` shall be set to 1.

**Comment by SwagPolice** [comment]
Thank you very much for your answer! Sorry for the incomprehension, this is all clear to me now.
